import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.lang.Exception;
import javax.swing.ImageIcon;

public class Add_to_Cart extends javax.swing.JFrame {

    int sum;
    /**
     * Creates new form f_Administration
     */
    public Add_to_Cart() {
        initComponents();
        //pan2.setVisible(false);
        White.setVisible(false);
        b1.setEnabled(false);
        All_C.setVisible(false);
        Act_C.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan4 = new javax.swing.JPanel();
        Cat = new javax.swing.JLabel();
        All = new javax.swing.JLabel();
        Act = new javax.swing.JLabel();
        All_C = new javax.swing.JLabel();
        Act_C = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        Back1 = new javax.swing.JPanel();
        Code1 = new javax.swing.JLabel();
        Black = new javax.swing.JLabel();
        White = new javax.swing.JLabel();
        pan1 = new javax.swing.JPanel();
        d1 = new javax.swing.JLabel();
        d2 = new javax.swing.JLabel();
        d3 = new javax.swing.JLabel();
        d4 = new javax.swing.JLabel();
        All3 = new javax.swing.JLabel();
        All5 = new javax.swing.JLabel();
        All6 = new javax.swing.JLabel();
        All7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        All2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        pan2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        All8 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pan4.setBackground(new java.awt.Color(246, 246, 246));
        pan4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cat.setFont(new java.awt.Font("Unispace", 1, 36)); // NOI18N
        Cat.setForeground(new java.awt.Color(0, 102, 204));
        Cat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cat.setText("Options");
        pan4.add(Cat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 70));

        All.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        All.setForeground(new java.awt.Color(28, 0, 28));
        All.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        All.setText(" Customer Details");
        All.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AllMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AllMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AllMouseExited(evt);
            }
        });
        pan4.add(All, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 210, 50));

        Act.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        Act.setForeground(new java.awt.Color(28, 0, 28));
        Act.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Act.setText(" Customer Orders");
        Act.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ActMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ActMouseExited(evt);
            }
        });
        pan4.add(Act, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 210, 50));

        All_C.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        All_C.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        All_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Grey.png"))); // NOI18N
        pan4.add(All_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 210, 50));

        Act_C.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        Act_C.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Act_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Grey.png"))); // NOI18N
        pan4.add(Act_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 210, 50));
        pan4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 190, 10));

        getContentPane().add(pan4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 210, 470));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Unispace", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Customer Details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1100, 70));

        l1.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        l1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, 90, 90));

        l2.setForeground(new java.awt.Color(24, 24, 24));
        jPanel1.add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 20, 20));

        l3.setForeground(new java.awt.Color(24, 24, 24));
        jPanel1.add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 40, 20, 20));

        l4.setForeground(new java.awt.Color(24, 24, 24));
        jPanel1.add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 70, 20, 20));

        Back1.setBackground(new java.awt.Color(255, 255, 255));
        Back1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Back1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Code1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Code1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Code1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Code1MouseExited(evt);
            }
        });
        Back1.add(Code1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 35, 35));

        Black.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        Black.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Black.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back1.png"))); // NOI18N
        Back1.add(Black, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 35, 35));

        White.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        White.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        White.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/White.png"))); // NOI18N
        Back1.add(White, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 35, 35));

        jPanel1.add(Back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 35, 35));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 110));

        pan1.setBackground(new java.awt.Color(255, 255, 255));
        pan1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d1.setFont(new java.awt.Font("Unispace", 1, 24)); // NOI18N
        d1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        d1.setText("Shivank Sharma");
        pan1.add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 430, 40));

        d2.setFont(new java.awt.Font("Unispace", 1, 24)); // NOI18N
        d2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        d2.setText("sshivank24@gmail.com");
        pan1.add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 430, 40));

        d3.setFont(new java.awt.Font("Unispace", 1, 24)); // NOI18N
        d3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        d3.setText("Shivank123");
        pan1.add(d3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 430, 40));

        d4.setFont(new java.awt.Font("Unispace", 1, 24)); // NOI18N
        d4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        d4.setText("9764563976");
        pan1.add(d4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 430, 40));

        All3.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        All3.setForeground(new java.awt.Color(51, 153, 255));
        All3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        All3.setText("Your Details -");
        pan1.add(All3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 220, 50));

        All5.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        All5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        All5.setText("Name : ");
        pan1.add(All5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 150, 40));

        All6.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        All6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        All6.setText("E - Mail : ");
        pan1.add(All6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 150, 40));

        All7.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        All7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        All7.setText("Username : ");
        pan1.add(All7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 150, 40));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Unispace", 1, 24)); // NOI18N
        jButton1.setText("Change Password");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pan1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 250, 50));

        All2.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        All2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        All2.setText("Contact No. : ");
        pan1.add(All2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 150, 40));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Unispace", 1, 24)); // NOI18N
        jButton2.setText("Log Out");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        pan1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 250, 50));

        getContentPane().add(pan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 890, 470));

        pan2.setBackground(new java.awt.Color(255, 255, 255));
        pan2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tab2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Game ID", "Game Name", "Platform", "Quantity", "Net Price", "Address", "Payment Mode", "Discount", "City"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab2.setRowSelectionAllowed(false);
        tab2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tab2);

        pan2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 830, 300));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jButton3.setText("Remove");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        pan2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 410, 120, 40));

        b1.setBackground(new java.awt.Color(255, 255, 255));
        b1.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        b1.setText("Purchase");
        b1.setToolTipText("");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        pan2.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 140, 40));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        jButton5.setText("Display Products");
        jButton5.setToolTipText("");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        pan2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 220, 40));

        All8.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        All8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        All8.setText("Game ID :");
        pan2.add(All8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 120, 30));

        t1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        pan2.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 360, 170, 30));

        getContentPane().add(pan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 890, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AllMouseClicked
        pan1.setVisible(true);
        pan2.setVisible(false);
    }//GEN-LAST:event_AllMouseClicked

    private void AllMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AllMouseEntered
        All_C.setVisible(true);
    }//GEN-LAST:event_AllMouseEntered

    private void AllMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AllMouseExited
        All_C.setVisible(false);
    }//GEN-LAST:event_AllMouseExited

    private void ActMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActMouseClicked
        pan1.setVisible(false);
        pan2.setVisible(true);
    }//GEN-LAST:event_ActMouseClicked

    private void ActMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActMouseEntered
        Act_C.setVisible(true);
    }//GEN-LAST:event_ActMouseEntered

    private void ActMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActMouseExited
        Act_C.setVisible(false);
    }//GEN-LAST:event_ActMouseExited

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String a = l3.getText();           //Username
        String ID = t1.getText();          //Game ID
        DefaultTableModel dtm = (DefaultTableModel)tab2.getModel();
        
        try
        {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/P","root","root");
            Statement st = con.createStatement();
            String qry = "Delete from buy where username = '" +a+ "' and Game_ID = '" +ID+ "' ;";
            int rs = st.executeUpdate(qry);
            JOptionPane.showMessageDialog(null,"Item from Cart is Removed","Item Removed",JOptionPane.INFORMATION_MESSAGE);
            b1.setEnabled(false);
            t1.setText("");
            while(dtm.getRowCount()>0)
            dtm.removeRow(0);          
        }
        
        catch (HeadlessException | ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Change_Password().setVisible(true);        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        String a = l3.getText();
        String b = Integer.toString(sum);
        
        Order_Placed f1 = new Order_Placed();
        f1.UN.setText(a);
        f1.Amt.setText(b);
        f1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_b1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String a = l3.getText();
        sum = 0;
                
        DefaultTableModel dtm = (DefaultTableModel)tab2.getModel();
        while(dtm.getRowCount()>0)
            dtm.removeRow(0);
        
        try
        {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/P","root","root");
            Statement st = con.createStatement();
            String qry = "Select * from buy where username = '" +a+ "' ;";
            ResultSet rs = st.executeQuery(qry);
            
            while(rs.next())
            {                
                String a1 = rs.getString("Game_ID");
                String b = rs.getString("Game_Name");
                String c = rs.getString("Platform");
                String d = rs.getString("Quantity");
                int e = rs.getInt("Net_Price");
                String f = rs.getString("Address");
                String g = rs.getString("payment_Mode");
                String h = rs.getString("Discount");
                String i = rs.getString("City");
                
                sum = sum + e;
                
                dtm.addRow(new Object[]{a1,b,c,d,e,f,g,h,i});
                
            }            
            b1.setEnabled(true);
        }
        
        catch (HeadlessException | ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String a = l2.getText();
        l1.setIcon(new ImageIcon(a));  
    }//GEN-LAST:event_formWindowOpened

    private void Code1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Code1MouseClicked
        Gamin_Main_Page f1 = new Gamin_Main_Page();
        f1.l2.setText(this.l2.getText());           // Address
        f1.l3.setText(this.l3.getText());           // Username
        f1.l4.setText("1");                         // Alphabets Checking

        f1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Code1MouseClicked

    private void Code1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Code1MouseEntered
        Black.setVisible(false);
        White.setVisible(true);
    }//GEN-LAST:event_Code1MouseEntered

    private void Code1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Code1MouseExited
        Black.setVisible(true);
        White.setVisible(false);
    }//GEN-LAST:event_Code1MouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(null,"Log Out","Log Out Sucessfully!!!",JOptionPane.INFORMATION_MESSAGE);
        new d_Login_1().setVisible(true);
        this.dispose();                        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Act;
    private javax.swing.JLabel Act_C;
    private javax.swing.JLabel All;
    private javax.swing.JLabel All2;
    private javax.swing.JLabel All3;
    private javax.swing.JLabel All5;
    private javax.swing.JLabel All6;
    private javax.swing.JLabel All7;
    private javax.swing.JLabel All8;
    private javax.swing.JLabel All_C;
    private javax.swing.JPanel Back1;
    private javax.swing.JLabel Black;
    private javax.swing.JLabel Cat;
    private javax.swing.JLabel Code1;
    public javax.swing.JLabel White;
    private javax.swing.JButton b1;
    public javax.swing.JLabel d1;
    public javax.swing.JLabel d2;
    public javax.swing.JLabel d3;
    public javax.swing.JLabel d4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel l1;
    public javax.swing.JLabel l2;
    public javax.swing.JLabel l3;
    public javax.swing.JLabel l4;
    public javax.swing.JPanel pan1;
    public javax.swing.JPanel pan2;
    private javax.swing.JPanel pan4;
    private javax.swing.JTextField t1;
    private javax.swing.JTable tab2;
    // End of variables declaration//GEN-END:variables
}
