import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class Administration extends javax.swing.JFrame {

    /**
     * Creates new form f_Administration
     */
    public Administration() {
        initComponents();
        pan2.setVisible(false);
        All_C.setVisible(false);
        Act_C.setVisible(false);
        White.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan4 = new javax.swing.JPanel();
        Cat = new javax.swing.JLabel();
        All = new javax.swing.JLabel();
        Act = new javax.swing.JLabel();
        All_C = new javax.swing.JLabel();
        Act_C = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Back1 = new javax.swing.JPanel();
        Code1 = new javax.swing.JLabel();
        Black = new javax.swing.JLabel();
        White = new javax.swing.JLabel();
        pan1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        pan2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab2 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pan4.setBackground(new java.awt.Color(246, 246, 246));
        pan4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cat.setFont(new java.awt.Font("Unispace", 1, 36)); // NOI18N
        Cat.setForeground(new java.awt.Color(0, 102, 204));
        Cat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cat.setText("Options");
        pan4.add(Cat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 70));

        All.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        All.setForeground(new java.awt.Color(28, 0, 28));
        All.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        All.setText(" Accounts");
        All.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AllMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AllMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AllMouseExited(evt);
            }
        });
        pan4.add(All, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 210, 50));

        Act.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        Act.setForeground(new java.awt.Color(28, 0, 28));
        Act.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Act.setText(" Orders Placed\n");
        Act.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ActMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ActMouseExited(evt);
            }
        });
        pan4.add(Act, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 210, 50));

        All_C.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        All_C.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        All_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Grey.png"))); // NOI18N
        pan4.add(All_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 210, 50));

        Act_C.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        Act_C.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Act_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Grey.png"))); // NOI18N
        pan4.add(Act_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 210, 50));
        pan4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 190, 10));

        getContentPane().add(pan4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 210, 470));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Unispace", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Administrator");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1300, 70));

        Back1.setBackground(new java.awt.Color(255, 255, 255));
        Back1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Back1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Code1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Code1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Code1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Code1MouseExited(evt);
            }
        });
        Back1.add(Code1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 35, 35));

        Black.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        Black.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Black.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back1.png"))); // NOI18N
        Back1.add(Black, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 35, 35));

        White.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        White.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        White.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/White.png"))); // NOI18N
        Back1.add(White, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 35, 35));

        jPanel1.add(Back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 35, 35));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 110));

        pan1.setBackground(new java.awt.Color(255, 255, 255));
        pan1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tab1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "E-Mail", "Username", "Password", "Contact No."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab1.setRowSelectionAllowed(false);
        tab1.getTableHeader().setResizingAllowed(false);
        tab1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tab1);

        pan1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 1010, 320));

        jButton1.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jButton1.setText("Display");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pan1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 120, 40));

        getContentPane().add(pan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 1090, 470));

        pan2.setBackground(new java.awt.Color(255, 255, 255));
        pan2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tab2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Game ID", "Username", "Game Name", "Platform", "Quantity", "Net Price", "Address", "Payment Mode", "Discount", "City"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab2.setRowSelectionAllowed(false);
        tab2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tab2);

        pan2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 1020, 300));

        jButton5.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jButton5.setText("Display Products");
        jButton5.setToolTipText("");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        pan2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 170, 40));

        getContentPane().add(pan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 1090, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AllMouseClicked
        pan1.setVisible(true);
        pan2.setVisible(false);
    }//GEN-LAST:event_AllMouseClicked

    private void AllMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AllMouseEntered
        All_C.setVisible(true);
    }//GEN-LAST:event_AllMouseEntered

    private void AllMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AllMouseExited
        All_C.setVisible(false);
    }//GEN-LAST:event_AllMouseExited

    private void ActMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActMouseClicked
        pan1.setVisible(false);
        pan2.setVisible(true);
    }//GEN-LAST:event_ActMouseClicked

    private void ActMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActMouseEntered
        Act_C.setVisible(true);
    }//GEN-LAST:event_ActMouseEntered

    private void ActMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActMouseExited
        Act_C.setVisible(false);
    }//GEN-LAST:event_ActMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel)tab1.getModel();
        while(dtm.getRowCount()>0)
        dtm.removeRow(0);
        
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/P","root","root");
            Statement st = con.createStatement();
            String qry = "Select * from acc ;";
            ResultSet rs = st.executeQuery(qry);
            
            while(rs.next())
            {                
                String a = rs.getString("FName");
                String b = rs.getString("LName");
                String c = rs.getString("EMail");
                String d = rs.getString("Username");
                String e = rs.getString("Password");
                String f = rs.getString("ContactNo");                
                
                dtm.addRow(new Object[]{a,b,c,d,e,f});                
            }                        
        }
        
        catch (HeadlessException | ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel)tab2.getModel();
        while(dtm.getRowCount()>0)
        dtm.removeRow(0);

        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/P","root","root");
            Statement st = con.createStatement();
            String qry = "Select * from admin ;";
            ResultSet rs = st.executeQuery(qry);

            while(rs.next())
            {
                String a1 = rs.getString("Username");
                String a2 = rs.getString("Game_ID");
                String b = rs.getString("Game_Name");
                String c = rs.getString("Platform");
                String d = rs.getString("Quantity");
                String e = rs.getString("Net_Price");
                String f = rs.getString("Address");
                String g = rs.getString("payment_Mode");
                String h = rs.getString("Discount");
                String i = rs.getString("City");               

                dtm.addRow(new Object[]{a2,a1,b,c,d,e,f,g,h,i});
            }            
        }

        catch (HeadlessException | ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void Code1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Code1MouseClicked
        new c_Create_Acc1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Code1MouseClicked

    private void Code1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Code1MouseEntered
        Black.setVisible(false);
        White.setVisible(true);
    }//GEN-LAST:event_Code1MouseEntered

    private void Code1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Code1MouseExited
        Black.setVisible(true);
        White.setVisible(false);
    }//GEN-LAST:event_Code1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Act;
    private javax.swing.JLabel Act_C;
    private javax.swing.JLabel All;
    private javax.swing.JLabel All_C;
    private javax.swing.JPanel Back1;
    private javax.swing.JLabel Black;
    private javax.swing.JLabel Cat;
    private javax.swing.JLabel Code1;
    public javax.swing.JLabel White;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pan1;
    private javax.swing.JPanel pan2;
    private javax.swing.JPanel pan4;
    private javax.swing.JTable tab1;
    private javax.swing.JTable tab2;
    // End of variables declaration//GEN-END:variables
}
