/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class b_Explore_1 extends javax.swing.JFrame {

    /**
     * Creates new form b_Features_1
     */
    public b_Explore_1() {
        initComponents();
        lab1_C.setVisible(false);
        lab2_C.setVisible(false);
        lab3_C.setVisible(false);
        lab4_C.setVisible(false);  
        Desc1.setVisible(false);
        Desc2.setVisible(false);
        Desc3.setVisible(false);
        Desc4.setVisible(false);
        lab3_C1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Close = new javax.swing.JPanel();
        lab5 = new javax.swing.JLabel();
        lab3_C1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        pan1 = new javax.swing.JPanel();
        More1 = new javax.swing.JLabel();
        lab1 = new javax.swing.JLabel();
        lab1_C = new javax.swing.JLabel();
        Desc1 = new javax.swing.JLabel();
        pan2 = new javax.swing.JPanel();
        More2 = new javax.swing.JLabel();
        lab2 = new javax.swing.JLabel();
        lab2_C = new javax.swing.JLabel();
        Desc2 = new javax.swing.JLabel();
        pan3 = new javax.swing.JPanel();
        More3 = new javax.swing.JLabel();
        lab3 = new javax.swing.JLabel();
        lab3_C = new javax.swing.JLabel();
        Desc3 = new javax.swing.JLabel();
        pan4 = new javax.swing.JPanel();
        More4 = new javax.swing.JLabel();
        lab4 = new javax.swing.JLabel();
        lab4_C = new javax.swing.JLabel();
        Desc4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Unispace", 1, 60)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("EXPLORE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 360, 70));

        Close.setBackground(new java.awt.Color(255, 255, 255));
        Close.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lab5.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        lab5.setForeground(new java.awt.Color(255, 0, 0));
        lab5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab5.setText("X");
        lab5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        lab5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lab5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lab5MouseExited(evt);
            }
        });
        Close.add(lab5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        lab3_C1.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        lab3_C1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab3_C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lab3_C.png"))); // NOI18N
        Close.add(lab3_C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        jPanel1.add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 0, 30, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 90));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Unispace", 0, 36)); // NOI18N
        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 480, 140, 60));

        pan1.setOpaque(false);
        pan1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        More1.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        More1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        More1.setText(">  ");
        More1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                More1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                More1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                More1MouseExited(evt);
            }
        });
        pan1.add(More1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 50));

        lab1.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        lab1.setText(" Buy Games from Us...");
        lab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lab1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lab1MouseExited(evt);
            }
        });
        pan1.add(lab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 50));

        lab1_C.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        lab1_C.setForeground(new java.awt.Color(0, 112, 224));
        lab1_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Grey.png"))); // NOI18N
        pan1.add(lab1_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 50));

        Desc1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        Desc1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Desc1.setText("<html><body>You can buy any game from this app and get more benifits like :- more discount , faster delivery , more payment methods , etc. ");
        Desc1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pan1.add(Desc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 800, 50));

        jPanel2.add(pan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 810, 110));

        pan2.setOpaque(false);
        pan2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        More2.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        More2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        More2.setText(">  ");
        More2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                More2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                More2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                More2MouseExited(evt);
            }
        });
        pan2.add(More2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 50));

        lab2.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        lab2.setText(" Games for All...");
        lab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lab2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lab2MouseExited(evt);
            }
        });
        pan2.add(lab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 50));

        lab2_C.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        lab2_C.setForeground(new java.awt.Color(0, 112, 224));
        lab2_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Grey.png"))); // NOI18N
        pan2.add(lab2_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 50));

        Desc2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        Desc2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Desc2.setText("<html><body>In this app you can buy latest varities of game for any platform like PS-3 ,Xbox 360 ,Xbox One ,PS-4 ,PC ,etc.");
        Desc2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pan2.add(Desc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 800, 50));

        jPanel2.add(pan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 810, 110));

        pan3.setOpaque(false);
        pan3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        More3.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        More3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        More3.setText(">  ");
        More3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                More3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                More3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                More3MouseExited(evt);
            }
        });
        pan3.add(More3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 50));

        lab3.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        lab3.setText(" Discounts on Festive Events...");
        lab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lab3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lab3MouseExited(evt);
            }
        });
        pan3.add(lab3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 50));

        lab3_C.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        lab3_C.setForeground(new java.awt.Color(0, 112, 224));
        lab3_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Grey.png"))); // NOI18N
        pan3.add(lab3_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 50));

        Desc3.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        Desc3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Desc3.setText("<html><body>Participate in the festive events to get discount voucher, free gifts and Gaming accessories.");
        Desc3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pan3.add(Desc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 800, 50));

        jPanel2.add(pan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 810, 110));

        pan4.setOpaque(false);
        pan4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        More4.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        More4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        More4.setText(">  ");
        More4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                More4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                More4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                More4MouseExited(evt);
            }
        });
        pan4.add(More4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 50));

        lab4.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        lab4.setText(" About Us...");
        lab4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lab4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lab4MouseExited(evt);
            }
        });
        pan4.add(lab4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 50));

        lab4_C.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        lab4_C.setForeground(new java.awt.Color(0, 112, 224));
        lab4_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Grey.png"))); // NOI18N
        pan4.add(lab4_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 50));

        Desc4.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        Desc4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Desc4.setText("<html><body>Made by - <b>Deepak Moolani , Shivank Sharma , Parag Dutt Sharma</b>");
        Desc4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pan4.add(Desc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 800, 50));

        jPanel2.add(pan4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 810, 110));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1180, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lab2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab2MouseEntered
        lab2_C.setVisible(true);
    }//GEN-LAST:event_lab2MouseEntered

    private void lab2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab2MouseExited
        lab2_C.setVisible(false);
    }//GEN-LAST:event_lab2MouseExited

    private void lab3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab3MouseEntered
        lab3_C.setVisible(true);
    }//GEN-LAST:event_lab3MouseEntered

    private void lab3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab3MouseExited
        lab3_C.setVisible(false);
    }//GEN-LAST:event_lab3MouseExited

    private void lab4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab4MouseEntered
        lab4_C.setVisible(true);
    }//GEN-LAST:event_lab4MouseEntered

    private void lab4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab4MouseExited
        lab4_C.setVisible(false);
    }//GEN-LAST:event_lab4MouseExited

    private void lab1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab1MouseEntered
        lab1_C.setVisible(true);
    }//GEN-LAST:event_lab1MouseEntered

    private void lab1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab1MouseExited
        lab1_C.setVisible(false);
    }//GEN-LAST:event_lab1MouseExited

    private void More1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_More1MouseClicked
        String a = More1.getText();
        if(a.equals(">  "))  
        {
            Desc1.setVisible(true);
            a = "<  ";
            More1.setText("" + a);
        }
        else
        {
            Desc1.setVisible(false);
            a = ">  ";
            More1.setText("" + a);
        }            
    }//GEN-LAST:event_More1MouseClicked

    private void More2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_More2MouseClicked
        String a = More2.getText();
        if(a.equals(">  "))  
        {
            Desc2.setVisible(true);
            a = "<  ";
            More2.setText("" + a);
        }    
        else
        {
            Desc2.setVisible(false);
            a = ">  ";
            More2.setText("" + a);
        }  
    }//GEN-LAST:event_More2MouseClicked

    private void More3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_More3MouseClicked
        String a = More3.getText();
        if(a.equals(">  "))  
        {
            Desc3.setVisible(true);
            a = "<  ";
            More3.setText("" + a);
        }    
        else
        {
            Desc3.setVisible(false);
            a = ">  ";
            More3.setText("" + a);
        }  
    }//GEN-LAST:event_More3MouseClicked

    private void More4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_More4MouseClicked
        String a = More4.getText();
        if(a.equals(">  "))  
        {
            Desc4.setVisible(true);
            a = "<  ";
            More4.setText("" + a);
        }    
        else
        {
            Desc4.setVisible(false);
            a = ">  ";
            More4.setText("" + a);
        }  
    }//GEN-LAST:event_More4MouseClicked

    private void More1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_More1MouseEntered
        lab1_C.setVisible(true);                                            
    }//GEN-LAST:event_More1MouseEntered

    private void More1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_More1MouseExited
        lab1_C.setVisible(false);
    }//GEN-LAST:event_More1MouseExited

    private void More2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_More2MouseEntered
        lab2_C.setVisible(true);  
    }//GEN-LAST:event_More2MouseEntered

    private void More2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_More2MouseExited
        lab2_C.setVisible(false);
    }//GEN-LAST:event_More2MouseExited

    private void More3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_More3MouseEntered
        lab3_C.setVisible(true);  
    }//GEN-LAST:event_More3MouseEntered

    private void More3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_More3MouseExited
        lab3_C.setVisible(false);
    }//GEN-LAST:event_More3MouseExited

    private void More4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_More4MouseEntered
        lab4_C.setVisible(true);  
    }//GEN-LAST:event_More4MouseEntered

    private void More4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_More4MouseExited
        lab4_C.setVisible(false);
    }//GEN-LAST:event_More4MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new c_Create_Acc1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lab5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab5MouseClicked
        this.dispose();
    }//GEN-LAST:event_lab5MouseClicked

    private void lab5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab5MouseEntered
        lab3_C1.setVisible(true);
        lab5.setForeground(new java.awt.Color(255,255,255));
        lab5.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_lab5MouseEntered

    private void lab5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab5MouseExited
        lab3_C1.setVisible(false);
        lab5.setForeground(new java.awt.Color(255,0,0));
        lab5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
    }//GEN-LAST:event_lab5MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(b_Explore_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(b_Explore_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(b_Explore_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(b_Explore_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new b_Explore_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Close;
    private javax.swing.JLabel Desc1;
    private javax.swing.JLabel Desc2;
    private javax.swing.JLabel Desc3;
    private javax.swing.JLabel Desc4;
    private javax.swing.JLabel More1;
    private javax.swing.JLabel More2;
    private javax.swing.JLabel More3;
    private javax.swing.JLabel More4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lab1;
    private javax.swing.JLabel lab1_C;
    private javax.swing.JLabel lab2;
    private javax.swing.JLabel lab2_C;
    private javax.swing.JLabel lab3;
    private javax.swing.JLabel lab3_C;
    public javax.swing.JLabel lab3_C1;
    private javax.swing.JLabel lab4;
    private javax.swing.JLabel lab4_C;
    private javax.swing.JLabel lab5;
    private javax.swing.JPanel pan1;
    private javax.swing.JPanel pan2;
    private javax.swing.JPanel pan3;
    private javax.swing.JPanel pan4;
    // End of variables declaration//GEN-END:variables
}
