
import java.awt.Frame;
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class c_Create_Acc1 extends javax.swing.JFrame {

    /**
     * Creates new form c_Create_Acc
     */
    public c_Create_Acc1() {
        initComponents();    
        lab3_C.setVisible(false);
        lab3_C1.setVisible(false);
        lab2_C.setVisible(false);
        pan1.setVisible(false);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lab3 = new javax.swing.JLabel();
        lab3_C = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pan1 = new javax.swing.JPanel();
        lab4 = new javax.swing.JLabel();
        lab3_C1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        p3 = new javax.swing.JPasswordField();
        lab2 = new javax.swing.JLabel();
        lab2_C = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        p1 = new javax.swing.JPasswordField();
        p2 = new javax.swing.JPasswordField();
        t5 = new javax.swing.JTextField();
        c1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lab3.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        lab3.setForeground(new java.awt.Color(255, 0, 0));
        lab3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab3.setText("X");
        lab3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        lab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lab3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lab3MouseExited(evt);
            }
        });
        jPanel3.add(lab3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        lab3_C.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        lab3_C.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab3_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lab3_C.png"))); // NOI18N
        jPanel3.add(lab3_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, 30, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pan1.setBackground(new java.awt.Color(255, 255, 255));
        pan1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pan1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lab4.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        lab4.setForeground(new java.awt.Color(255, 0, 0));
        lab4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab4.setText("X");
        lab4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        lab4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lab4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lab4MouseExited(evt);
            }
        });
        pan1.add(lab4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 30, 30));

        lab3_C1.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        lab3_C1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab3_C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lab3_C.png"))); // NOI18N
        pan1.add(lab3_C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 30, 30));

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Enter Password :");
        pan1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 150, 30));

        p3.setFont(new java.awt.Font("Roboto Light", 0, 15)); // NOI18N
        pan1.add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 210, 30));

        lab2.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        lab2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab2.setText("Sign In");
        lab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lab2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lab2MouseExited(evt);
            }
        });
        pan1.add(lab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 130, 40));

        lab2_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Grey.png"))); // NOI18N
        pan1.add(lab2_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 130, 40));

        jLabel19.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Administrator");
        pan1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 40));

        jPanel2.add(pan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, 370, 150));

        jLabel5.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Last Name :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 220, 30));

        jLabel6.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("E-Mail ID :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 220, 30));

        jLabel7.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Username :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 220, 30));

        jLabel8.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Password :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 220, 30));

        t1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        t1.setToolTipText("Enter your First Name");
        jPanel2.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 230, 30));

        t2.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        t2.setToolTipText("Enter you last Name");
        jPanel2.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 230, 30));

        t3.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jPanel2.add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 230, 30));

        t4.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        t4.setToolTipText("Make sure your usename does not exceeds 25 characters");
        jPanel2.add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 230, 30));

        p1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        p1.setToolTipText("your Password must contain a small letter, a capital Letter and a digit value");
        jPanel2.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 230, 30));

        p2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jPanel2.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 230, 30));

        t5.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        t5.setToolTipText("Make Sure your contact exceeds 10 characters ..");
        jPanel2.add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 230, 30));

        c1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        c1.setText("Show Password");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        jPanel2.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 140, 20));

        jButton1.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        jButton1.setText("Sign Up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, -1, 30));

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 0, 204));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Administrator");
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel16MouseExited(evt);
            }
        });
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 100, 30));

        jLabel10.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Contact No.  :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 220, 30));

        jLabel11.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Confirm Password :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 220, 30));

        jLabel12.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("First Name :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 220, 30));

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 0, 204));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Log In");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 500, 60, 30));

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Already have a account ? ");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, -1, 30));

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("*By signing in you are accepting our ");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 500, -1, 30));

        jLabel17.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 0, 204));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Terms of Service");
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 500, 110, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Side_1.jpg"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 540));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1050, 540));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Unispace", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Account");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 110));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*String fn = t1.getText();
        String ln = t2.getText();
        String em = t3.getText();
        String us = t4.getText();
        String ps = new String(p1.getPassword());
        String cps = new String(p2.getPassword());
        String cn = t5.getText();        
        
        try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/P","root","root");
            Statement st = con.createStatement();            
            
            if(ps.equals(cps))
            {                                                                                                         
                String qry = "Insert into Acc values('" +fn+ "','" +ln+ "','" +em+ "','" +us+ "','" +ps+ "','" +cn+ "');";                                
                int rs = st.executeUpdate(qry);
                    
                JOptionPane.showMessageDialog(null,"User Regester Sucessfully..");
                new d_Login_1().setVisible(true);
                this.dispose();
            }
            else
            {                
                JOptionPane.showMessageDialog(null,"Password and Confirm Password not equal...");
                t1.setText("");
                t2.setText("");
                t3.setText("");
                t4.setText("");
                t5.setText("");
                p1.setText("");
                p2.setText("");
                c1.setSelected(false);
                t1.requestFocus();
            }
        }
        
        catch (SQLException | ClassNotFoundException | HeadlessException e)
        {            
            JOptionPane.showMessageDialog(null,e.getMessage());
        }*/
        
        
        String fn = t1.getText();
        String ln = t2.getText();
        String em = t3.getText();
        String us = t4.getText();
        String ps = new String(p1.getPassword());
        String cps = new String(p2.getPassword());
        String cn = t5.getText();  
        
        if(fn.isEmpty() || ln.isEmpty() || em.isEmpty() || us.isEmpty() || ps.isEmpty() || ps.isEmpty() || cps.isEmpty() || cn.isEmpty())
        {            
            JOptionPane.showMessageDialog(null,"Please fill all the Feilds...");
        }   
        else
        {
            int count=0;
        if(us.length()<=25 && ps.length()>=8)
        {
            count++;
        }
        
        for(int i = 0 ; i < ps.length() ; i++)
            {
            if(ps.charAt(i) >= 48 && ps.charAt(i)<=57)                        
            {count++;               
            break;}
            }   
            for(int i = 0 ; i < ps.length() ; i++)
            {
                if(ps.charAt(i) >= 65 && ps.charAt(i)<=90)                        
                {count++;               
                break;}
            }
            for(int i = 0 ; i < ps.length() ; i++)
            {
                if(ps.charAt(i) >= 97 && ps.charAt(i)<=122)                        
                {count++;               
                break;}
            }
            if (count==4)
            {
                try {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/p","root","root");
            Statement st = con.createStatement();            
            
            if(ps.equals(cps))
            {                                                                                                         
                String qry = "Insert into Acc values('" +fn+ "','" +ln+ "','" +em+ "','" +us+ "','" +ps+ "','" +cn+ "');";                                
                int rs = st.executeUpdate(qry);
                    
                JOptionPane.showMessageDialog(null,"User Regester Sucessfully..");
                new d_Login_1().setVisible(true);
                this.dispose();
            }
            else
            {                
                JOptionPane.showMessageDialog(null,"Password and Confirm Password not equal...");
                t1.setText("");
                t2.setText("");
                t3.setText("");
                t4.setText("");
                t5.setText("");
                p1.setText("");
                p2.setText("");
                c1.setSelected(false);
                t1.requestFocus();
            }
        }
        
        catch (SQLException | ClassNotFoundException | HeadlessException e)
        {            
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Please Follow the instructions given...");
            }
        }
        
                    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        new d_Login_1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        if(c1.isSelected())
        {
            p1.setEchoChar((char)0);
            p2.setEchoChar((char)0);
        }
        
        else
        {
            p1.setEchoChar('*');
            p2.setEchoChar('*');
        }        
    }//GEN-LAST:event_c1ActionPerformed

    private void lab3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab3MouseClicked
        this.dispose();
    }//GEN-LAST:event_lab3MouseClicked

    private void lab3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab3MouseEntered
        lab3_C.setVisible(true);
        lab3.setForeground(new java.awt.Color(255,255,255));
        lab3.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_lab3MouseEntered

    private void lab3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab3MouseExited
        lab3_C.setVisible(false);
        lab3.setForeground(new java.awt.Color(255,0,0));
        lab3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
    }//GEN-LAST:event_lab3MouseExited

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        pan1.setVisible(true);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void lab4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab4MouseClicked
        pan1.setVisible(false);
    }//GEN-LAST:event_lab4MouseClicked

    private void lab4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab4MouseEntered
        lab3_C1.setVisible(true);
        lab4.setForeground(new java.awt.Color(255,255,255));
        lab4.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_lab4MouseEntered

    private void lab4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab4MouseExited
        lab3_C1.setVisible(false);
        lab4.setForeground(new java.awt.Color(255,0,0));
        lab4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
    }//GEN-LAST:event_lab4MouseExited

    private void lab2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab2MouseClicked
        String b = new String(p3.getPassword());
        
        if(b.equals("MyGamin"))
        {
            JOptionPane.showMessageDialog(null,"<html><body><font face='Roboto light' size = 4>Welcome Site Owners...");
            new Administration().setVisible(true);
            this.dispose();
        }
        else
            JOptionPane.showMessageDialog(null,"<html><body><font face='Roboto light' size = 4>Password not Correct !!!");
    }//GEN-LAST:event_lab2MouseClicked

    private void lab2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab2MouseEntered
        lab2_C.setVisible(true);
    }//GEN-LAST:event_lab2MouseEntered

    private void lab2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab2MouseExited
        lab2_C.setVisible(false);
    }//GEN-LAST:event_lab2MouseExited

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
        jLabel16.setText("<html><body><U>Administrator</U>");        
    }//GEN-LAST:event_jLabel16MouseEntered

    private void jLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseExited
        jLabel16.setText("Administrator");
    }//GEN-LAST:event_jLabel16MouseExited

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        jLabel13.setText("<html><body><U>Log In</U>");        
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        jLabel13.setText("Log In");
    }//GEN-LAST:event_jLabel13MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(c_Create_Acc1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(c_Create_Acc1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(c_Create_Acc1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(c_Create_Acc1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new c_Create_Acc1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox c1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lab2;
    private javax.swing.JLabel lab2_C;
    private javax.swing.JLabel lab3;
    private javax.swing.JLabel lab3_C;
    private javax.swing.JLabel lab3_C1;
    private javax.swing.JLabel lab4;
    private javax.swing.JPasswordField p1;
    private javax.swing.JPasswordField p2;
    public javax.swing.JPasswordField p3;
    private javax.swing.JPanel pan1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    // End of variables declaration//GEN-END:variables
}
