import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class Change_Password extends javax.swing.JFrame {    

    /**
     * Creates new form d_Login_1
     */
    public Change_Password() {
        initComponents();
        lab2_C.setVisible(false);
        lab3_C.setVisible(false);
        Check1.setVisible(false);
        Check2.setVisible(false);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Check1 = new javax.swing.JLabel();
        Check2 = new javax.swing.JLabel();
        lab3 = new javax.swing.JLabel();
        lab3_C = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        p1 = new javax.swing.JPasswordField();
        p2 = new javax.swing.JPasswordField();
        c1 = new javax.swing.JCheckBox();
        lab2 = new javax.swing.JLabel();
        lab2_C = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        NP = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jButton1.setText("Check");
        jButton1.setToolTipText("Click here for check your password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 80, 30));

        Check1.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        Check1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Check1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Check.png"))); // NOI18N
        jPanel2.add(Check1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 30, 30));

        Check2.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        Check2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Check2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Check2.png"))); // NOI18N
        jPanel2.add(Check2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 30, 30));

        lab3.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        lab3.setForeground(new java.awt.Color(255, 0, 0));
        lab3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab3.setText("X");
        lab3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        lab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lab3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lab3MouseExited(evt);
            }
        });
        jPanel2.add(lab3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 30, 30));

        lab3_C.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        lab3_C.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab3_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lab3_C.png"))); // NOI18N
        jPanel2.add(lab3_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 30, 30));

        t1.setFont(new java.awt.Font("Roboto Light", 0, 15)); // NOI18N
        jPanel2.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 190, 30));

        p1.setFont(new java.awt.Font("Roboto Light", 0, 15)); // NOI18N
        jPanel2.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 190, 30));

        p2.setFont(new java.awt.Font("Roboto Light", 0, 15)); // NOI18N
        p2.setEnabled(false);
        jPanel2.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 190, 30));

        c1.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        c1.setText("Show Password");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        jPanel2.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        lab2.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        lab2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab2.setText("Change Password");
        lab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lab2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lab2MouseExited(evt);
            }
        });
        jPanel2.add(lab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 240, 40));

        lab2_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Grey.png"))); // NOI18N
        jPanel2.add(lab2_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 240, 40));

        jLabel10.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel10.setText("Username :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 90, 30));

        jLabel9.setFont(new java.awt.Font("Segoe Print", 0, 30)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Change Password");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 400, 50));

        NP.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        NP.setText("New Password :");
        NP.setEnabled(false);
        jPanel2.add(NP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 30));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel4.setText("Old Password :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 120, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        if(c1.isSelected())
        {
            p1.setEchoChar((char)0);
            p2.setEchoChar((char)0);
        }        
        else
        {
            p1.setEchoChar('*');
            p2.setEchoChar('*');
        }        
    }//GEN-LAST:event_c1ActionPerformed

    private void lab2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab2MouseClicked
        String a = t1.getText();
        String b = new String(p1.getPassword());        
        String c = new String(p2.getPassword());        
        
        try
        {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/P","root","root");
            Statement st = con.createStatement();
                                                                                                                                
                String qry1 = "Update Acc set password = '" +c+ "' where username = '" +a+ "' ;";
                String qry2 = "Update LogIn_1 set password = '" +c+ "' where username = '" +a+ "' ;";
                int rs1 = st.executeUpdate(qry1);
                int rs2 = st.executeUpdate(qry2);
                    
                JOptionPane.showMessageDialog(null,"Password Changed..");                
                this.dispose();                                
                                    
            st.close();
            con.close();
        }
        catch (SQLException | ClassNotFoundException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_lab2MouseClicked

    private void lab2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab2MouseEntered
        lab2_C.setVisible(true);
    }//GEN-LAST:event_lab2MouseEntered

    private void lab2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab2MouseExited
        lab2_C.setVisible(false);
    }//GEN-LAST:event_lab2MouseExited

    private void lab3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab3MouseClicked
        this.dispose();
    }//GEN-LAST:event_lab3MouseClicked

    private void lab3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab3MouseEntered
        lab3_C.setVisible(true);
        lab3.setForeground(new java.awt.Color(255,255,255));
        lab3.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_lab3MouseEntered

    private void lab3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab3MouseExited
        lab3_C.setVisible(false);
        lab3.setForeground(new java.awt.Color(255,0,0));
        lab3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
    }//GEN-LAST:event_lab3MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String a = t1.getText();
        String b = new String(p1.getPassword());        
        
        try
        {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/P","root","root");
            Statement st = con.createStatement();
            String qry = "Select * from acc where username = '" +a+ "' and password = '" +b+ "';";
            ResultSet rs = st.executeQuery(qry);            
            
            if(rs.next())
            {                
                JOptionPane.showMessageDialog(null,"Right Password...");
                p1.setBackground(new java.awt.Color(243, 255, 243));                       
                Check1.setVisible(true);
                Check2.setVisible(false);
                NP.setEnabled(true);
                p2.setEnabled(true);
            }                        

            else
            {
                JOptionPane.showMessageDialog(null,"Invalid Username or Password!!");
                p1.setBackground(new java.awt.Color(255, 243, 243));                
                Check2.setVisible(true);
                Check1.setVisible(false);
                t1.setText("");
                p1.setText("");
                t1.requestFocus();
            }
            rs.close();
            st.close();
            con.close();
        }
        catch (SQLException | ClassNotFoundException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Change_Password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Check1;
    private javax.swing.JLabel Check2;
    private javax.swing.JLabel NP;
    private javax.swing.JCheckBox c1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lab2;
    private javax.swing.JLabel lab2_C;
    private javax.swing.JLabel lab3;
    private javax.swing.JLabel lab3_C;
    public javax.swing.JPasswordField p1;
    public javax.swing.JPasswordField p2;
    public javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
