import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class d_Login_1 extends javax.swing.JFrame {    

    /**
     * Creates new form d_Login_1
     */
    public d_Login_1() {
        initComponents();
        lab2_C.setVisible(false);
        lab3_C.setVisible(false);
        Check2.setVisible(false);                
        Msg.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lab3 = new javax.swing.JLabel();
        lab3_C = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        p1 = new javax.swing.JPasswordField();
        c1 = new javax.swing.JCheckBox();
        lab2 = new javax.swing.JLabel();
        lab2_C = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Check2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Msg = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lab3.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        lab3.setForeground(new java.awt.Color(255, 0, 0));
        lab3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab3.setText("X");
        lab3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        lab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lab3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lab3MouseExited(evt);
            }
        });
        jPanel2.add(lab3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 30, 30));

        lab3_C.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        lab3_C.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab3_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lab3_C.png"))); // NOI18N
        jPanel2.add(lab3_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 30, 30));

        jLabel3.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Password :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 130, 30));

        t1.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        jPanel2.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 210, 30));

        p1.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        jPanel2.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 210, 30));

        c1.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        c1.setText("Show Password");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        jPanel2.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, 30));

        lab2.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        lab2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab2.setText("Log In");
        lab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lab2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lab2MouseExited(evt);
            }
        });
        jPanel2.add(lab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 200, 40));

        lab2_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Grey.png"))); // NOI18N
        jPanel2.add(lab2_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 200, 40));

        jLabel10.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Username :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 130, 30));

        jLabel9.setFont(new java.awt.Font("Unispace", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("GameQiop");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 440, 70));

        Check2.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        Check2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Check2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Check2.png"))); // NOI18N
        jPanel2.add(Check2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 30, 30));

        jLabel17.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 0, 204));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Create new Account");
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel17MouseExited(evt);
            }
        });
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 150, 30));

        Msg.setFont(new java.awt.Font("Unispace", 0, 16)); // NOI18N
        Msg.setForeground(new java.awt.Color(255, 51, 51));
        Msg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Msg.setText("Invalid username or password !!");
        Msg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(Msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 440, 30));

        jLabel19.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 153, 153));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Do not have an account ?");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 190, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        if(c1.isSelected())
        p1.setEchoChar((char)0);
        else
        p1.setEchoChar('*');
    }//GEN-LAST:event_c1ActionPerformed

    private void lab2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab2MouseClicked
        String a = t1.getText();
        String b = new String(p1.getPassword());
        String nm = "", UN = "";
        
        try
        {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/P","root","root");
            Statement st = con.createStatement();
            String qry = "Select * from acc where username = '" +a+ "' and password = '" +b+ "';";
            ResultSet rs = st.executeQuery(qry);

            if(rs.next())
            {
                JOptionPane.showMessageDialog(null,"Welcome User...");
                nm = rs.getString("Fname");
                UN = rs.getString("Username");
                nm = nm.substring(0,1);
                
                Gamin_Main_Page f1 = new Gamin_Main_Page();
              //  f1.l1.setText(nm);
                f1.l3.setText(UN);
                f1.l5.setText("0");
                
                f1.setVisible(true);
                this.dispose();
            }                        

            else
            {                
                p1.setBackground(new java.awt.Color(255, 243, 243));                
                Check2.setVisible(true);
                Msg.setVisible(true);
                t1.setText("");
                p1.setText("");
                t1.requestFocus();
            }
            rs.close();
            st.close();
            con.close();
        }
        catch (SQLException | ClassNotFoundException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_lab2MouseClicked

    private void lab2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab2MouseEntered
        lab2_C.setVisible(true);
    }//GEN-LAST:event_lab2MouseEntered

    private void lab2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab2MouseExited
        lab2_C.setVisible(false);        
    }//GEN-LAST:event_lab2MouseExited

    private void lab3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab3MouseClicked
        this.dispose();
    }//GEN-LAST:event_lab3MouseClicked

    private void lab3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab3MouseEntered
        lab3_C.setVisible(true);
        lab3.setForeground(new java.awt.Color(255,255,255));
        lab3.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_lab3MouseEntered

    private void lab3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab3MouseExited
        lab3_C.setVisible(false);
        lab3.setForeground(new java.awt.Color(255,0,0));
        lab3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
    }//GEN-LAST:event_lab3MouseExited

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        new c_Create_Acc1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseEntered
        jLabel17.setText("<html><body><U>Create new Account</U>");                                                    
    }//GEN-LAST:event_jLabel17MouseEntered

    private void jLabel17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseExited
        jLabel17.setText("Create new Account");
    }//GEN-LAST:event_jLabel17MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(d_Login_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(d_Login_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(d_Login_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(d_Login_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new d_Login_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Check2;
    private javax.swing.JLabel Msg;
    private javax.swing.JCheckBox c1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lab2;
    private javax.swing.JLabel lab2_C;
    private javax.swing.JLabel lab3;
    private javax.swing.JLabel lab3_C;
    public javax.swing.JPasswordField p1;
    public javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
