import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class Gamin_Main_Page extends javax.swing.JFrame {
    
    public String add;        
    /**
     * Creates new form d_Feature1
     */
    public Gamin_Main_Page() {
        initComponents();
      
        jLabel37.setVisible(false);
        jLabel35.setVisible(false);
        jLabel3.setVisible(false);
        jLabel31.setVisible(false);
        jLabel29.setVisible(false);
        jLabel27.setVisible(false);
        jLabel25.setVisible(false);
        jLabel23.setVisible(false);
        jLabel21.setVisible(false);
        jLabel19.setVisible(false);
        jLabel18.setVisible(false);
        jLabel17.setVisible(false);
        jLabel13.setVisible(false);
        jLabel12.setVisible(false);
        jLabel11.setVisible(false);
        jLabel7.setVisible(false);
        jLabel5.setVisible(false);
        jLabel33.setVisible(false);
        Assassin_Creed_C.setVisible(false);
        Call_of_Duty_C.setVisible(false);
        Need_for_Speed_C.setVisible(false);
        Grand_Theft_Auto_C.setVisible(false);
        Tom_Clancy_C.setVisible(false);
        Far_Cry_C.setVisible(false);
        Forza_Horizon_C.setVisible(false);
        Horizon_Zero_Dawn_C.setVisible(false);
        PUB_C.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pan4 = new javax.swing.JPanel();
        Cat = new javax.swing.JLabel();
        Assassin_Creed = new javax.swing.JLabel();
        Call_of_Duty = new javax.swing.JLabel();
        Need_for_Speed = new javax.swing.JLabel();
        Grand_Theft_Auto = new javax.swing.JLabel();
        Tom_Clancy = new javax.swing.JLabel();
        Far_Cry = new javax.swing.JLabel();
        Forza_Horizon = new javax.swing.JLabel();
        Horizon_Zero_Dawn = new javax.swing.JLabel();
        PUB = new javax.swing.JLabel();
        Assassin_Creed_C = new javax.swing.JLabel();
        Call_of_Duty_C = new javax.swing.JLabel();
        Need_for_Speed_C = new javax.swing.JLabel();
        Grand_Theft_Auto_C = new javax.swing.JLabel();
        Tom_Clancy_C = new javax.swing.JLabel();
        Far_Cry_C = new javax.swing.JLabel();
        Forza_Horizon_C = new javax.swing.JLabel();
        Horizon_Zero_Dawn_C = new javax.swing.JLabel();
        PUB_C = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panel1_Assassins_Creed = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Part2 = new javax.swing.JButton();
        Part1 = new javax.swing.JButton();
        Part3 = new javax.swing.JButton();
        panel2_COD = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Part6 = new javax.swing.JButton();
        Part7 = new javax.swing.JButton();
        Part8 = new javax.swing.JButton();
        panel3_NFS = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Part11 = new javax.swing.JButton();
        Part12 = new javax.swing.JButton();
        Part13 = new javax.swing.JButton();
        panel4_GTA = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Part16 = new javax.swing.JButton();
        Part17 = new javax.swing.JButton();
        panel5_Tom_Clancy = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        Part21 = new javax.swing.JButton();
        Part22 = new javax.swing.JButton();
        panel6_Far_Cry = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        Part26 = new javax.swing.JButton();
        Part27 = new javax.swing.JButton();
        panel7_Forza_Horizon = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Part31 = new javax.swing.JButton();
        panel8_Horizon_Zero_Dawn = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        Part36 = new javax.swing.JButton();
        panel9_PUB = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        Part41 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Unispace", 0, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("GameQiop");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 330, 90));

        jButton1.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jButton1.setText("Your Cart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 60, 110, 40));
        jPanel1.add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 10, 20, 20));

        l3.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 255, 255));
        l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 20, 110, 40));
        jPanel1.add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 70, 20, 20));
        jPanel1.add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 70, 20, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 110));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pan4.setBackground(new java.awt.Color(246, 246, 246));
        pan4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cat.setFont(new java.awt.Font("Unispace", 1, 36)); // NOI18N
        Cat.setForeground(new java.awt.Color(0, 102, 204));
        Cat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cat.setText("Games");
        pan4.add(Cat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 70));

        Assassin_Creed.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        Assassin_Creed.setForeground(new java.awt.Color(28, 0, 28));
        Assassin_Creed.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Assassin_Creed.setText(" Assassin's Creed");
        Assassin_Creed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Assassin_CreedMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Assassin_CreedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Assassin_CreedMouseExited(evt);
            }
        });
        pan4.add(Assassin_Creed, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 240, 50));

        Call_of_Duty.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        Call_of_Duty.setForeground(new java.awt.Color(28, 0, 28));
        Call_of_Duty.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Call_of_Duty.setText(" Call of Duty");
        Call_of_Duty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Call_of_DutyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Call_of_DutyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Call_of_DutyMouseExited(evt);
            }
        });
        pan4.add(Call_of_Duty, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 240, 50));

        Need_for_Speed.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        Need_for_Speed.setForeground(new java.awt.Color(28, 0, 28));
        Need_for_Speed.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Need_for_Speed.setText(" Need for Speed");
        Need_for_Speed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Need_for_SpeedMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Need_for_SpeedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Need_for_SpeedMouseExited(evt);
            }
        });
        pan4.add(Need_for_Speed, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 240, 50));

        Grand_Theft_Auto.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        Grand_Theft_Auto.setForeground(new java.awt.Color(28, 0, 28));
        Grand_Theft_Auto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Grand_Theft_Auto.setText(" Grand Theft Auto");
        Grand_Theft_Auto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Grand_Theft_AutoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Grand_Theft_AutoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Grand_Theft_AutoMouseExited(evt);
            }
        });
        pan4.add(Grand_Theft_Auto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 240, 50));

        Tom_Clancy.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        Tom_Clancy.setForeground(new java.awt.Color(28, 0, 28));
        Tom_Clancy.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Tom_Clancy.setText(" Tom Clancy");
        Tom_Clancy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tom_ClancyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Tom_ClancyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Tom_ClancyMouseExited(evt);
            }
        });
        pan4.add(Tom_Clancy, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 240, 50));

        Far_Cry.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        Far_Cry.setForeground(new java.awt.Color(28, 0, 28));
        Far_Cry.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Far_Cry.setText(" Far Cry");
        Far_Cry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Far_CryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Far_CryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Far_CryMouseExited(evt);
            }
        });
        pan4.add(Far_Cry, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 240, 50));

        Forza_Horizon.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        Forza_Horizon.setForeground(new java.awt.Color(28, 0, 28));
        Forza_Horizon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Forza_Horizon.setText(" Forza Horizon");
        Forza_Horizon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Forza_HorizonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Forza_HorizonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Forza_HorizonMouseExited(evt);
            }
        });
        pan4.add(Forza_Horizon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 240, 50));

        Horizon_Zero_Dawn.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        Horizon_Zero_Dawn.setForeground(new java.awt.Color(28, 0, 28));
        Horizon_Zero_Dawn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Horizon_Zero_Dawn.setText(" Horizon Zero Dawn");
        Horizon_Zero_Dawn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Horizon_Zero_DawnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Horizon_Zero_DawnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Horizon_Zero_DawnMouseExited(evt);
            }
        });
        pan4.add(Horizon_Zero_Dawn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 240, 50));

        PUB.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        PUB.setForeground(new java.awt.Color(28, 0, 28));
        PUB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PUB.setText(" PUBG");
        PUB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PUBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PUBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PUBMouseExited(evt);
            }
        });
        pan4.add(PUB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 240, 50));

        Assassin_Creed_C.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        Assassin_Creed_C.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Assassin_Creed_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Grey.png"))); // NOI18N
        pan4.add(Assassin_Creed_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 240, 50));

        Call_of_Duty_C.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        Call_of_Duty_C.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Call_of_Duty_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Grey.png"))); // NOI18N
        pan4.add(Call_of_Duty_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 240, 50));

        Need_for_Speed_C.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        Need_for_Speed_C.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Need_for_Speed_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Grey.png"))); // NOI18N
        pan4.add(Need_for_Speed_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 240, 50));

        Grand_Theft_Auto_C.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        Grand_Theft_Auto_C.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Grand_Theft_Auto_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Grey.png"))); // NOI18N
        pan4.add(Grand_Theft_Auto_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 240, 50));

        Tom_Clancy_C.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        Tom_Clancy_C.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Tom_Clancy_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Grey.png"))); // NOI18N
        pan4.add(Tom_Clancy_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 240, 50));

        Far_Cry_C.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        Far_Cry_C.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Far_Cry_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Grey.png"))); // NOI18N
        pan4.add(Far_Cry_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 240, 50));

        Forza_Horizon_C.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        Forza_Horizon_C.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Forza_Horizon_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Grey.png"))); // NOI18N
        pan4.add(Forza_Horizon_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 240, 50));

        Horizon_Zero_Dawn_C.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        Horizon_Zero_Dawn_C.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Horizon_Zero_Dawn_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Grey.png"))); // NOI18N
        pan4.add(Horizon_Zero_Dawn_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 240, 50));

        PUB_C.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        PUB_C.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PUB_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Grey.png"))); // NOI18N
        pan4.add(PUB_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 240, 50));
        pan4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 240, 10));

        jPanel2.add(pan4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 550));

        panel1_Assassins_Creed.setBackground(new java.awt.Color(255, 255, 255));
        panel1_Assassins_Creed.setPreferredSize(new java.awt.Dimension(1060, 2470));
        panel1_Assassins_Creed.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Newone/AC_1.png"))); // NOI18N
        panel1_Assassins_Creed.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 210, 210));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shaded/AC_1_Shaded.jpg"))); // NOI18N
        panel1_Assassins_Creed.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 210, 210));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Newone/AC_2.jpg"))); // NOI18N
        panel1_Assassins_Creed.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 210, 210));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shaded/AC_2_Shaded.jpg"))); // NOI18N
        panel1_Assassins_Creed.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 210, 210));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Newone/AC_3.jpg"))); // NOI18N
        panel1_Assassins_Creed.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 210, 210));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shaded/AC_3_Shaded.jpg"))); // NOI18N
        panel1_Assassins_Creed.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 210, 210));

        Part2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Part2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Part2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Part2MouseExited(evt);
            }
        });
        Part2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Part2ActionPerformed(evt);
            }
        });
        panel1_Assassins_Creed.add(Part2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 230, 230));

        Part1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Part1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Part1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Part1MouseExited(evt);
            }
        });
        Part1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Part1ActionPerformed(evt);
            }
        });
        panel1_Assassins_Creed.add(Part1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 230, 230));

        Part3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Part3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Part3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Part3MouseExited(evt);
            }
        });
        Part3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Part3ActionPerformed(evt);
            }
        });
        panel1_Assassins_Creed.add(Part3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 230, 230));

        jPanel2.add(panel1_Assassins_Creed, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1060, 530));

        panel2_COD.setBackground(new java.awt.Color(255, 255, 255));
        panel2_COD.setPreferredSize(new java.awt.Dimension(1060, 2470));
        panel2_COD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Newone/COD_1.jpg"))); // NOI18N
        panel2_COD.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 210, 210));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shaded/COD_3_Shaded.jpg"))); // NOI18N
        panel2_COD.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 210, 210));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Newone/COD_2.png"))); // NOI18N
        panel2_COD.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 210, 210));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shaded/COD_1_Shaded.jpg"))); // NOI18N
        panel2_COD.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 210, 210));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Newone/COD_3.jpg"))); // NOI18N
        panel2_COD.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 210, 210));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shaded/COD_2_Shaded.jpg"))); // NOI18N
        panel2_COD.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 210, 210));

        Part6.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Part6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Part6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Part6MouseExited(evt);
            }
        });
        Part6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Part6ActionPerformed(evt);
            }
        });
        panel2_COD.add(Part6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 230, 230));

        Part7.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Part7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Part7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Part7MouseExited(evt);
            }
        });
        Part7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Part7ActionPerformed(evt);
            }
        });
        panel2_COD.add(Part7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 230, 230));

        Part8.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Part8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Part8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Part8MouseExited(evt);
            }
        });
        Part8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Part8ActionPerformed(evt);
            }
        });
        panel2_COD.add(Part8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 230, 230));

        jPanel2.add(panel2_COD, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1060, 550));

        panel3_NFS.setBackground(new java.awt.Color(255, 255, 255));
        panel3_NFS.setPreferredSize(new java.awt.Dimension(1060, 2470));
        panel3_NFS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Newone/NFS_1.jpg"))); // NOI18N
        panel3_NFS.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 210, 210));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shaded/NFS_2_Shaded.jpg"))); // NOI18N
        panel3_NFS.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 210, 210));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Newone/NFS_2.jpg"))); // NOI18N
        panel3_NFS.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 210, 210));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shaded/NFS_3_Shaded.jpg"))); // NOI18N
        panel3_NFS.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 210, 210));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Newone/NFS_3.jpg"))); // NOI18N
        panel3_NFS.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 210, 210));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shaded/NFS_1_Shaded.jpg"))); // NOI18N
        panel3_NFS.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 210, 210));

        Part11.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Part11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Part11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Part11MouseExited(evt);
            }
        });
        Part11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Part11ActionPerformed(evt);
            }
        });
        panel3_NFS.add(Part11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 230, 230));

        Part12.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Part12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Part12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Part12MouseExited(evt);
            }
        });
        Part12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Part12ActionPerformed(evt);
            }
        });
        panel3_NFS.add(Part12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 230, 230));

        Part13.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Part13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Part13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Part13MouseExited(evt);
            }
        });
        Part13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Part13ActionPerformed(evt);
            }
        });
        panel3_NFS.add(Part13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 230, 230));

        jPanel2.add(panel3_NFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1060, 550));

        panel4_GTA.setBackground(new java.awt.Color(255, 255, 255));
        panel4_GTA.setPreferredSize(new java.awt.Dimension(1060, 2470));
        panel4_GTA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Newone/GTA_1.jpg"))); // NOI18N
        panel4_GTA.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 210, 210));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shaded/GTA_1_Shaded.jpg"))); // NOI18N
        panel4_GTA.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 210, 210));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Newone/GTA_2.jpg"))); // NOI18N
        panel4_GTA.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 210, 210));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shaded/GTA_2_Shaded.jpg"))); // NOI18N
        panel4_GTA.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 210, 210));

        Part16.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Part16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Part16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Part16MouseExited(evt);
            }
        });
        Part16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Part16ActionPerformed(evt);
            }
        });
        panel4_GTA.add(Part16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 230, 230));

        Part17.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Part17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Part17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Part17MouseExited(evt);
            }
        });
        Part17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Part17ActionPerformed(evt);
            }
        });
        panel4_GTA.add(Part17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 230, 230));

        jPanel2.add(panel4_GTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1060, 550));

        panel5_Tom_Clancy.setBackground(new java.awt.Color(255, 255, 255));
        panel5_Tom_Clancy.setPreferredSize(new java.awt.Dimension(1060, 2470));
        panel5_Tom_Clancy.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Newone/TC_1.jpg"))); // NOI18N
        panel5_Tom_Clancy.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 210, 210));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shaded/TC_1_Shaded.png"))); // NOI18N
        panel5_Tom_Clancy.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 210, 210));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Newone/TC_2.jpg"))); // NOI18N
        panel5_Tom_Clancy.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 210, 210));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shaded/TC_2_Shaded.jpg"))); // NOI18N
        panel5_Tom_Clancy.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 210, 210));

        Part21.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Part21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Part21MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Part21MouseExited(evt);
            }
        });
        Part21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Part21ActionPerformed(evt);
            }
        });
        panel5_Tom_Clancy.add(Part21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 230, 230));

        Part22.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Part22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Part22MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Part22MouseExited(evt);
            }
        });
        Part22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Part22ActionPerformed(evt);
            }
        });
        panel5_Tom_Clancy.add(Part22, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 230, 230));

        jPanel2.add(panel5_Tom_Clancy, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1060, 550));

        panel6_Far_Cry.setBackground(new java.awt.Color(255, 255, 255));
        panel6_Far_Cry.setPreferredSize(new java.awt.Dimension(1060, 2470));
        panel6_Far_Cry.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Newone/FC_2.jpg"))); // NOI18N
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel28MouseEntered(evt);
            }
        });
        panel6_Far_Cry.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 210, 210));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shaded/FC_2_Shaded.jpg"))); // NOI18N
        panel6_Far_Cry.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 210, 210));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Newone/FC_1.jpg"))); // NOI18N
        panel6_Far_Cry.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 210, 210));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shaded/FC_1_Shaded.jpg"))); // NOI18N
        panel6_Far_Cry.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 210, 210));

        Part26.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Part26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Part26MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Part26MouseExited(evt);
            }
        });
        Part26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Part26ActionPerformed(evt);
            }
        });
        panel6_Far_Cry.add(Part26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 230, 230));

        Part27.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Part27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Part27MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Part27MouseExited(evt);
            }
        });
        Part27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Part27ActionPerformed(evt);
            }
        });
        panel6_Far_Cry.add(Part27, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 230, 230));

        jPanel2.add(panel6_Far_Cry, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1060, 550));

        panel7_Forza_Horizon.setBackground(new java.awt.Color(255, 255, 255));
        panel7_Forza_Horizon.setPreferredSize(new java.awt.Dimension(1060, 2470));
        panel7_Forza_Horizon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Newone/FH_1.jpg"))); // NOI18N
        panel7_Forza_Horizon.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 210, 210));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shaded/FZ_3_Shaded.jpg"))); // NOI18N
        panel7_Forza_Horizon.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 210, 210));

        Part31.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Part31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Part31MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Part31MouseExited(evt);
            }
        });
        Part31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Part31ActionPerformed(evt);
            }
        });
        panel7_Forza_Horizon.add(Part31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 230, 230));

        jPanel2.add(panel7_Forza_Horizon, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1060, 550));

        panel8_Horizon_Zero_Dawn.setBackground(new java.awt.Color(255, 255, 255));
        panel8_Horizon_Zero_Dawn.setPreferredSize(new java.awt.Dimension(1060, 2470));
        panel8_Horizon_Zero_Dawn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Newone/HZD_1.jpg"))); // NOI18N
        panel8_Horizon_Zero_Dawn.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 210, 210));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shaded/HZD_Shaded.jpg"))); // NOI18N
        panel8_Horizon_Zero_Dawn.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 210, 210));

        Part36.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Part36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Part36MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Part36MouseExited(evt);
            }
        });
        Part36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Part36ActionPerformed(evt);
            }
        });
        panel8_Horizon_Zero_Dawn.add(Part36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 230, 230));

        jPanel2.add(panel8_Horizon_Zero_Dawn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1060, 550));

        panel9_PUB.setBackground(new java.awt.Color(255, 255, 255));
        panel9_PUB.setPreferredSize(new java.awt.Dimension(1060, 2470));
        panel9_PUB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Newone/PUBG_1.jpg"))); // NOI18N
        panel9_PUB.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 210, 210));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Shaded/PUBG_Shaded.jpg"))); // NOI18N
        panel9_PUB.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 210, 210));

        Part41.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Part41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Part41MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Part41MouseExited(evt);
            }
        });
        Part41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Part41ActionPerformed(evt);
            }
        });
        panel9_PUB.add(Part41, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 230, 230));

        jPanel2.add(panel9_PUB, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1060, 550));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1300, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Assassin_CreedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Assassin_CreedMouseEntered
   Assassin_Creed_C.setVisible(true);
    }//GEN-LAST:event_Assassin_CreedMouseEntered

    private void Assassin_CreedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Assassin_CreedMouseExited
  Assassin_Creed_C.setVisible(false);
    }//GEN-LAST:event_Assassin_CreedMouseExited

    private void Call_of_DutyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Call_of_DutyMouseEntered
    Call_of_Duty_C.setVisible(true);
    }//GEN-LAST:event_Call_of_DutyMouseEntered

    private void Call_of_DutyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Call_of_DutyMouseExited
    Call_of_Duty_C.setVisible(false);
    }//GEN-LAST:event_Call_of_DutyMouseExited

    private void Need_for_SpeedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Need_for_SpeedMouseEntered
    Need_for_Speed_C.setVisible(true);
    }//GEN-LAST:event_Need_for_SpeedMouseEntered

    private void Need_for_SpeedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Need_for_SpeedMouseExited
    Need_for_Speed_C.setVisible(false);
    }//GEN-LAST:event_Need_for_SpeedMouseExited

    private void Grand_Theft_AutoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Grand_Theft_AutoMouseEntered
    Grand_Theft_Auto_C.setVisible(true);
    }//GEN-LAST:event_Grand_Theft_AutoMouseEntered

    private void Grand_Theft_AutoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Grand_Theft_AutoMouseExited
    Grand_Theft_Auto_C.setVisible(false);
    }//GEN-LAST:event_Grand_Theft_AutoMouseExited

    private void Tom_ClancyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tom_ClancyMouseEntered
    Tom_Clancy_C.setVisible(true);
    }//GEN-LAST:event_Tom_ClancyMouseEntered

    private void Tom_ClancyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tom_ClancyMouseExited
    Tom_Clancy_C.setVisible(false);
    }//GEN-LAST:event_Tom_ClancyMouseExited

    private void Far_CryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Far_CryMouseEntered
    Far_Cry_C.setVisible(true);
    }//GEN-LAST:event_Far_CryMouseEntered

    private void Far_CryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Far_CryMouseExited
    Far_Cry_C.setVisible(false);
    }//GEN-LAST:event_Far_CryMouseExited

    private void Assassin_CreedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Assassin_CreedMouseClicked
    panel1_Assassins_Creed.setVisible(true);
    panel2_COD.setVisible(false);
    panel3_NFS.setVisible(false);
    panel4_GTA.setVisible(false);
    panel5_Tom_Clancy.setVisible(false);
    panel6_Far_Cry.setVisible(false);
    panel7_Forza_Horizon.setVisible(false);
    panel8_Horizon_Zero_Dawn.setVisible(false);
    panel9_PUB.setVisible(false);
    }//GEN-LAST:event_Assassin_CreedMouseClicked

    private void Call_of_DutyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Call_of_DutyMouseClicked
    panel1_Assassins_Creed.setVisible(false);
    panel2_COD.setVisible(true);
    panel3_NFS.setVisible(false);
    panel4_GTA.setVisible(false);
    panel5_Tom_Clancy.setVisible(false);
    panel6_Far_Cry.setVisible(false);
    panel7_Forza_Horizon.setVisible(false);
    panel8_Horizon_Zero_Dawn.setVisible(false);
    panel9_PUB.setVisible(false);
    }//GEN-LAST:event_Call_of_DutyMouseClicked

    private void Tom_ClancyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tom_ClancyMouseClicked
    panel1_Assassins_Creed.setVisible(false);
    panel2_COD.setVisible(false);
    panel3_NFS.setVisible(false);
    panel4_GTA.setVisible(false);
    panel5_Tom_Clancy.setVisible(true);
    panel6_Far_Cry.setVisible(false);
    panel7_Forza_Horizon.setVisible(false);
    panel8_Horizon_Zero_Dawn.setVisible(false);
    panel9_PUB.setVisible(false);
    }//GEN-LAST:event_Tom_ClancyMouseClicked

    private void Need_for_SpeedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Need_for_SpeedMouseClicked
    panel1_Assassins_Creed.setVisible(false);
    panel2_COD.setVisible(false);
    panel3_NFS.setVisible(true);
    panel4_GTA.setVisible(false);
    panel5_Tom_Clancy.setVisible(false);
    panel6_Far_Cry.setVisible(false);
    panel7_Forza_Horizon.setVisible(false);
    panel8_Horizon_Zero_Dawn.setVisible(false);
    panel9_PUB.setVisible(false);
    }//GEN-LAST:event_Need_for_SpeedMouseClicked

    private void Grand_Theft_AutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Grand_Theft_AutoMouseClicked
    panel1_Assassins_Creed.setVisible(false);
    panel2_COD.setVisible(false);
    panel3_NFS.setVisible(false);
    panel4_GTA.setVisible(true);
    panel5_Tom_Clancy.setVisible(false);
    panel6_Far_Cry.setVisible(false);
    panel7_Forza_Horizon.setVisible(false);
    panel8_Horizon_Zero_Dawn.setVisible(false);
    panel9_PUB.setVisible(false);
    }//GEN-LAST:event_Grand_Theft_AutoMouseClicked

    private void Far_CryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Far_CryMouseClicked
    panel1_Assassins_Creed.setVisible(false);
    panel2_COD.setVisible(false);
    panel3_NFS.setVisible(false);
    panel4_GTA.setVisible(false);
    panel5_Tom_Clancy.setVisible(false);
    panel6_Far_Cry.setVisible(true);
    panel7_Forza_Horizon.setVisible(false);
    panel8_Horizon_Zero_Dawn.setVisible(false);
    panel9_PUB.setVisible(false);
    }//GEN-LAST:event_Far_CryMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//    String flag = l5.getText();         // Condition for 0 and 1
//        
//    if(flag.equals("0"))
//    {
//        String nm = l1.getText();       // Letter                               
//        
//        switch (nm) {
//            case "A":
//            case "a":
//                l1.setIcon(new ImageIcon("C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\a.jpg"));
//                add = "C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\a.jpg";
//                break;
//            case "B":
//            case "b":
//                l1.setIcon(new ImageIcon("C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\b.jpg"));
//                add = "C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\b.jpg";
//                break;
//            case "C":
//            case "c":
//                l1.setIcon(new ImageIcon("C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\c.jpg"));
//                add = "C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\c.jpg";
//                break;
//            case "D":
//            case "d":
//                l1.setIcon(new ImageIcon("C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\d.jpg"));
//                add = "C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\d.jpg";
//                break;
//            case "E":
//            case "e":
//                l1.setIcon(new ImageIcon("C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\e.jpg"));
//                add = "C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\e.jpg";
//                break;
//            case "F":
//            case "f":
//                l1.setIcon(new ImageIcon("C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\f.jpg"));
//                add = "C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\f.jpg";
//                break;
//            case "G":
//            case "g":
//                l1.setIcon(new ImageIcon("C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\g.jpg"));
//                add = "C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\g.jpg";
//                break;
//            case "H":
//            case "h":
//                l1.setIcon(new ImageIcon("C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\h.jpg"));
//                add = "C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\h.jpg";
//                break;
//            case "I":
//            case "i":
//                l1.setIcon(new ImageIcon("C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\i.jpg"));
//                add = "C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\i.jpg";
//                break;
//            case "J":
//            case "j":
//                l1.setIcon(new ImageIcon("C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\j.jpg"));
//                add = "C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\j.jpg";
//                break;
//            case "K":
//            case "k":
//                l1.setIcon(new ImageIcon("C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\k.jpg"));
//                add = "C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\k.jpg";
//                break;
//            case "L":
//            case "l":
//                l1.setIcon(new ImageIcon("C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\l.jpg"));
//                add = "C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\l.jpg";
//                break;
//            case "M":
//            case "m":
//                l1.setIcon(new ImageIcon("C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\m.jpg"));
//                add = "C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\m.jpg";
//                break;
//            case "N":
//            case "n":
//                l1.setIcon(new ImageIcon("C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\n.jpg"));
//                add = "C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\n.jpg";
//                break;
//            case "O":
//            case "o":
//                l1.setIcon(new ImageIcon("C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\o.jpg"));
//                add = "C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\o.jpg";
//                break;
//            case "P":
//            case "p":
//                l1.setIcon(new ImageIcon("C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\p.jpg"));
//                add = "C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\p.jpg";
//                break;
//            case "Q":
//            case "q":
//                l1.setIcon(new ImageIcon("C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\q.jpg"));
//                add = "C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\q.jpg";
//                break;
//            case "R":
//            case "r":
//                l1.setIcon(new ImageIcon("C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\r.jpg"));
//                add = "C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\r.jpg";
//                break;
//            case "S":
//            case "s":
//                l1.setIcon(new ImageIcon("C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\s.jpg"));
//                add = "C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\s.jpg";
//                break;                
//            case "T":
//            case "t":
//                l1.setIcon(new ImageIcon("C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\t.jpg"));
//                add = "C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\t.jpg";
//                break;
//            case "U":
//            case "u":
//                l1.setIcon(new ImageIcon("C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\u.jpg"));
//                add = "C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\u.jpg";
//                break;
//            case "V":
//            case "v":
//                l1.setIcon(new ImageIcon("C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\v.jpg"));
//                add = "C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\v.jpg";
//                break;
//            case "W":
//            case "w":
//                l1.setIcon(new ImageIcon("C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\w.jpg"));
//                add = "C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\w.jpg";
//                break;
//            case "X":
//            case "x":
//                l1.setIcon(new ImageIcon("C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\x.jpg"));
//                add = "C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\x.jpg";
//                break;
//            case "Y":
//            case "y":
//                l1.setIcon(new ImageIcon("C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\y.jpg"));
//                add = "C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\y.jpg";
//                break;
//            case "Z":
//            case "z":
//                l1.setIcon(new ImageIcon("C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\z.jpg"));
//                add = "C:\\Users\\Deepak\\Documents\\NetBeansProjects\\Final Project\\src\\Alphabets\\z.jpg";
//                break;
//            default:
//                break;
//        }
//        l2.setText("" + add);               // Address
//    }
//        String i = l4.getText();            // Working in TOP Classes
//        
//        if(i.equals("1"))
//        {
//            String a = l2.getText();        // Address
//            l1.setIcon(new ImageIcon(a));            
//        }
    }//GEN-LAST:event_formWindowOpened

    private void Forza_HorizonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Forza_HorizonMouseClicked
    panel1_Assassins_Creed.setVisible(false);
    panel2_COD.setVisible(false);
    panel3_NFS.setVisible(false);
    panel4_GTA.setVisible(false);
    panel5_Tom_Clancy.setVisible(false);
    panel6_Far_Cry.setVisible(false);
    panel7_Forza_Horizon.setVisible(true);
    panel8_Horizon_Zero_Dawn.setVisible(false);
    panel9_PUB.setVisible(false);
    }//GEN-LAST:event_Forza_HorizonMouseClicked

    private void Forza_HorizonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Forza_HorizonMouseEntered
        Forza_Horizon_C.setVisible(true);
    }//GEN-LAST:event_Forza_HorizonMouseEntered

    private void Forza_HorizonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Forza_HorizonMouseExited
        Forza_Horizon_C.setVisible(false);
    }//GEN-LAST:event_Forza_HorizonMouseExited

    private void Horizon_Zero_DawnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Horizon_Zero_DawnMouseClicked
    panel1_Assassins_Creed.setVisible(false);
    panel2_COD.setVisible(false);
    panel3_NFS.setVisible(false);
    panel4_GTA.setVisible(false);
    panel5_Tom_Clancy.setVisible(false);
    panel6_Far_Cry.setVisible(false);
    panel7_Forza_Horizon.setVisible(false);
    panel8_Horizon_Zero_Dawn.setVisible(true);
    panel9_PUB.setVisible(false);
    }//GEN-LAST:event_Horizon_Zero_DawnMouseClicked

    private void Horizon_Zero_DawnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Horizon_Zero_DawnMouseEntered
        Horizon_Zero_Dawn_C.setVisible(true);
    }//GEN-LAST:event_Horizon_Zero_DawnMouseEntered

    private void Horizon_Zero_DawnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Horizon_Zero_DawnMouseExited
        Horizon_Zero_Dawn_C.setVisible(false);
    }//GEN-LAST:event_Horizon_Zero_DawnMouseExited

    private void PUBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PUBMouseClicked
    panel1_Assassins_Creed.setVisible(false);
    panel2_COD.setVisible(false);
    panel3_NFS.setVisible(false);
    panel4_GTA.setVisible(false);
    panel5_Tom_Clancy.setVisible(false);
    panel6_Far_Cry.setVisible(false);
    panel7_Forza_Horizon.setVisible(false);
    panel8_Horizon_Zero_Dawn.setVisible(false);
    panel9_PUB.setVisible(true);
    }//GEN-LAST:event_PUBMouseClicked

    private void PUBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PUBMouseEntered
        PUB_C.setVisible(true);
    }//GEN-LAST:event_PUBMouseEntered

    private void PUBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PUBMouseExited
       PUB_C.setVisible(false);
    }//GEN-LAST:event_PUBMouseExited

    private void Part3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Part3ActionPerformed
        TOP_Assassins_Creed_3 f1 = new TOP_Assassins_Creed_3();
        f1.l2.setText(this.l2.getText());
        f1.l3.setText(this.l3.getText());

        f1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Part3ActionPerformed

    private void Part2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Part2ActionPerformed
        TOP_Assassins_Creed_2 f1 = new TOP_Assassins_Creed_2();
        f1.l2.setText(this.l2.getText());
        f1.l3.setText(this.l3.getText());

        f1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Part2ActionPerformed

    private void Part1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Part1ActionPerformed
        TOP_Assassins_Creed_1 f1 = new TOP_Assassins_Creed_1();
        f1.l2.setText(this.l2.getText());
        f1.l3.setText(this.l3.getText());

        f1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Part1ActionPerformed

    private void Part6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Part6ActionPerformed
        TOP_Call_of_Duty_1 f1 = new TOP_Call_of_Duty_1();
        f1.l2.setText(this.l2.getText());
        f1.l3.setText(this.l3.getText());

        f1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Part6ActionPerformed

    private void Part7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Part7ActionPerformed
        TOP_Call_of_Duty_2 f1 = new TOP_Call_of_Duty_2();
        f1.l2.setText(this.l2.getText());
        f1.l3.setText(this.l3.getText());

        f1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Part7ActionPerformed

    private void Part8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Part8ActionPerformed
        TOP_Call_of_Duty_3 f1 = new TOP_Call_of_Duty_3();
        f1.l2.setText(this.l2.getText());
        f1.l3.setText(this.l3.getText());

        f1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Part8ActionPerformed

    private void Part11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Part11ActionPerformed
        TOP_Need_for_Speed_1 f1 = new TOP_Need_for_Speed_1();
        f1.l2.setText(this.l2.getText());
        f1.l3.setText(this.l3.getText());

        f1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Part11ActionPerformed

    private void Part12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Part12ActionPerformed
        TOP_Need_for_Speed_2 f1 = new TOP_Need_for_Speed_2();
        f1.l2.setText(this.l2.getText());
        f1.l3.setText(this.l3.getText());

        f1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Part12ActionPerformed

    private void Part13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Part13ActionPerformed
        TOP_Need_for_Speed_3 f1 = new TOP_Need_for_Speed_3();
        f1.l2.setText(this.l2.getText());
        f1.l3.setText(this.l3.getText());

        f1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Part13ActionPerformed

    private void Part16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Part16ActionPerformed
        TOP_Grand_Theft_Auto_1 f1 = new TOP_Grand_Theft_Auto_1();
        f1.l2.setText(this.l2.getText());
        f1.l3.setText(this.l3.getText());

        f1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Part16ActionPerformed

    private void Part17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Part17ActionPerformed
        TOP_Grand_Theft_Auto_2 f1 = new TOP_Grand_Theft_Auto_2();
        f1.l2.setText(this.l2.getText());
        f1.l3.setText(this.l3.getText());

        f1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Part17ActionPerformed

    private void Part21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Part21ActionPerformed
        TOP_Tom_Clancy_1 f1 = new TOP_Tom_Clancy_1();
        f1.l2.setText(this.l2.getText());
        f1.l3.setText(this.l3.getText());
        
        f1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Part21ActionPerformed

    private void Part22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Part22ActionPerformed
        TOP_Tom_Clancy_2 f1 = new TOP_Tom_Clancy_2();
        f1.l2.setText(this.l2.getText());
        f1.l3.setText(this.l3.getText());
        
        f1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Part22ActionPerformed

    private void Part26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Part26ActionPerformed
        TOP_Far_Cry_1 f1 = new TOP_Far_Cry_1();
        f1.l2.setText(this.l2.getText());
        f1.l3.setText(this.l3.getText());
        
        f1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Part26ActionPerformed

    private void Part27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Part27ActionPerformed
        TOP_Far_Cry_2 f1 = new TOP_Far_Cry_2();
        f1.l2.setText(this.l2.getText());
        f1.l3.setText(this.l3.getText());
        
        f1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Part27ActionPerformed

    private void Part31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Part31ActionPerformed
        TOP_Forza_Horizon_1 f1 = new TOP_Forza_Horizon_1();
        f1.l2.setText(this.l2.getText());
        f1.l3.setText(this.l3.getText());
        
        f1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Part31ActionPerformed

    private void Part36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Part36ActionPerformed
        TOP_Horizon_Zero_Dawn_1 f1 = new TOP_Horizon_Zero_Dawn_1();
        f1.l2.setText(this.l2.getText());
        f1.l3.setText(this.l3.getText());
        
        f1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Part36ActionPerformed

    private void Part41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Part41ActionPerformed
        TOP_PUBG_1 f1 = new TOP_PUBG_1();
        f1.l2.setText(this.l2.getText());
        f1.l3.setText(this.l3.getText());
        
        f1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Part41ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String a = l3.getText();        
        
        try
        {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/P","root","root");
            Statement st = con.createStatement();
            String qry = "Select * from acc where username = '" +a+ "';";
            ResultSet rs = st.executeQuery(qry);

            if(rs.next())
            {                                                                                
                Add_to_Cart f1 = new Add_to_Cart();
                f1.l2.setText(this.l2.getText());  //letter address
                f1.l3.setText(this.l3.getText());  //username
                //f1.l5.setText("0");
                
                String b = rs.getString("FName");
                String c = rs.getString("LName");
                String d = rs.getString("EMail");                
                String f = rs.getString("ContactNo");
                
                f1.d1.setText(b + " " + c);
                f1.d2.setText(d);
                f1.d3.setText(this.l3.getText());
                f1.d4.setText(f);
                f1.pan1.setVisible(false);
                f1.pan2.setVisible(true);
                
                f1.setVisible(true);
                this.dispose();
            }                        
            
            rs.close();
            st.close();
            con.close();
        }
        catch (SQLException | ClassNotFoundException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Part1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part1MouseEntered
//    jLabel32.setVisible(false);
 //   jLabel33.setVisible(true);
    }//GEN-LAST:event_Part1MouseEntered

    private void Part1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part1MouseExited
//    jLabel33.setVisible(false);
//    jLabel32.setVisible(true);
    }//GEN-LAST:event_Part1MouseExited

    private void Part2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part2MouseEntered
//    jLabel4.setVisible(false);
//    jLabel5.setVisible(true);
    }//GEN-LAST:event_Part2MouseEntered

    private void Part2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part2MouseExited
//    jLabel5.setVisible(false);
//    jLabel4.setVisible(true);
    }//GEN-LAST:event_Part2MouseExited

    private void Part3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part3MouseEntered
//    jLabel7.setVisible(true);
//    jLabel6.setVisible(false);
    }//GEN-LAST:event_Part3MouseEntered

    private void Part3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part3MouseExited
//    jLabel6.setVisible(true);
//    jLabel7.setVisible(false);
    }//GEN-LAST:event_Part3MouseExited

    private void Part6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part6MouseEntered
//    jLabel9.setVisible(false);
//    jLabel11.setVisible(true);
    }//GEN-LAST:event_Part6MouseEntered

    private void Part6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part6MouseExited
//    jLabel11.setVisible(false);
//    jLabel9.setVisible(true);
    }//GEN-LAST:event_Part6MouseExited

    private void Part7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part7MouseEntered
//    jLabel12.setVisible(true);
//    jLabel10.setVisible(false);
    }//GEN-LAST:event_Part7MouseEntered

    private void Part7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part7MouseExited
 //   jLabel12.setVisible(false);
 //   jLabel10.setVisible(true);
    }//GEN-LAST:event_Part7MouseExited

    private void Part8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part8MouseEntered
//    jLabel8.setVisible(false);
//    jLabel13.setVisible(true);
    }//GEN-LAST:event_Part8MouseEntered

    private void Part8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part8MouseExited
//    jLabel8.setVisible(true);
//    jLabel13.setVisible(false);
    }//GEN-LAST:event_Part8MouseExited

    private void Part11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part11MouseEntered
//    jLabel18.setVisible(true);
//    jLabel15.setVisible(false);
    }//GEN-LAST:event_Part11MouseEntered

    private void Part11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part11MouseExited
//    jLabel18.setVisible(false);
//    jLabel15.setVisible(true);
    }//GEN-LAST:event_Part11MouseExited

    private void Part12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part12MouseEntered
//    jLabel17.setVisible(true);
//    jLabel16.setVisible(false);
    }//GEN-LAST:event_Part12MouseEntered

    private void Part12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part12MouseExited
//    jLabel16.setVisible(true);
//    jLabel17.setVisible(false);
    }//GEN-LAST:event_Part12MouseExited

    private void Part13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part13MouseEntered
 //   jLabel19.setVisible(true);
 //   jLabel14.setVisible(false);
    }//GEN-LAST:event_Part13MouseEntered

    private void Part13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part13MouseExited
 //   jLabel14.setVisible(true);
 //   jLabel19.setVisible(false);
    }//GEN-LAST:event_Part13MouseExited

    private void Part16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part16MouseEntered
 //   jLabel21.setVisible(true);
  //  jLabel20.setVisible(false);
    }//GEN-LAST:event_Part16MouseEntered

    private void Part16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part16MouseExited
 //   jLabel20.setVisible(true);
 //   jLabel21.setVisible(false);
    }//GEN-LAST:event_Part16MouseExited

    private void Part17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part17MouseEntered
 //   jLabel23.setVisible(true);
 //   jLabel22.setVisible(false);   
    }//GEN-LAST:event_Part17MouseEntered

    private void Part17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part17MouseExited
 //   jLabel22.setVisible(true);
 //   jLabel23.setVisible(false);
    }//GEN-LAST:event_Part17MouseExited

    private void Part21MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part21MouseEntered
 //   jLabel25.setVisible(true);
 //   jLabel24.setVisible(false);
    }//GEN-LAST:event_Part21MouseEntered

    private void Part21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part21MouseExited
 //   jLabel24.setVisible(true);
 //  jLabel25.setVisible(false);
    }//GEN-LAST:event_Part21MouseExited

    private void Part22MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part22MouseEntered
 //   jLabel27.setVisible(true);
 //   jLabel26.setVisible(false);
    }//GEN-LAST:event_Part22MouseEntered

    private void Part22MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part22MouseExited
 //   jLabel26.setVisible(true);
 //   jLabel27.setVisible(false);
    }//GEN-LAST:event_Part22MouseExited

    private void Part26MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part26MouseEntered
 //   jLabel31.setVisible(true);
 //   jLabel30.setVisible(false);
    }//GEN-LAST:event_Part26MouseEntered

    private void Part26MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part26MouseExited
  //  jLabel30.setVisible(true);
  //  jLabel31.setVisible(false);
    }//GEN-LAST:event_Part26MouseExited

    private void Part27MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part27MouseEntered
 //   jLabel29.setVisible(true);
 //   jLabel28.setVisible(false);
    }//GEN-LAST:event_Part27MouseEntered

    private void jLabel28MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseEntered
  //  jLabel29.setVisible(true);
  //  jLabel28.setVisible(false);
    }//GEN-LAST:event_jLabel28MouseEntered

    private void Part27MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part27MouseExited
  //  jLabel28.setVisible(true);
  //  jLabel29.setVisible(false);
    }//GEN-LAST:event_Part27MouseExited

    private void Part31MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part31MouseEntered
  //  jLabel3.setVisible(true);
   // jLabel2.setVisible(false);
    }//GEN-LAST:event_Part31MouseEntered

    private void Part31MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part31MouseExited
  //  jLabel2.setVisible(true);
  //  jLabel3.setVisible(false);
    }//GEN-LAST:event_Part31MouseExited

    private void Part36MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part36MouseEntered
 //   jLabel35.setVisible(true);
 //   jLabel34.setVisible(false);
    }//GEN-LAST:event_Part36MouseEntered

    private void Part36MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part36MouseExited
 //   jLabel34.setVisible(true);
 //   jLabel35.setVisible(false);
    }//GEN-LAST:event_Part36MouseExited

    private void Part41MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part41MouseEntered
 //   jLabel37.setVisible(true);
 //   jLabel36.setVisible(false);
    }//GEN-LAST:event_Part41MouseEntered

    private void Part41MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Part41MouseExited
  //  jLabel36.setVisible(true);
  //  jLabel37.setVisible(false);
    }//GEN-LAST:event_Part41MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gamin_Main_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gamin_Main_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gamin_Main_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gamin_Main_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gamin_Main_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Assassin_Creed;
    private javax.swing.JLabel Assassin_Creed_C;
    private javax.swing.JLabel Call_of_Duty;
    private javax.swing.JLabel Call_of_Duty_C;
    private javax.swing.JLabel Cat;
    private javax.swing.JLabel Far_Cry;
    private javax.swing.JLabel Far_Cry_C;
    private javax.swing.JLabel Forza_Horizon;
    private javax.swing.JLabel Forza_Horizon_C;
    private javax.swing.JLabel Grand_Theft_Auto;
    private javax.swing.JLabel Grand_Theft_Auto_C;
    private javax.swing.JLabel Horizon_Zero_Dawn;
    private javax.swing.JLabel Horizon_Zero_Dawn_C;
    private javax.swing.JLabel Need_for_Speed;
    private javax.swing.JLabel Need_for_Speed_C;
    private javax.swing.JLabel PUB;
    private javax.swing.JLabel PUB_C;
    private javax.swing.JButton Part1;
    private javax.swing.JButton Part11;
    private javax.swing.JButton Part12;
    private javax.swing.JButton Part13;
    private javax.swing.JButton Part16;
    private javax.swing.JButton Part17;
    private javax.swing.JButton Part2;
    private javax.swing.JButton Part21;
    private javax.swing.JButton Part22;
    private javax.swing.JButton Part26;
    private javax.swing.JButton Part27;
    private javax.swing.JButton Part3;
    private javax.swing.JButton Part31;
    private javax.swing.JButton Part36;
    private javax.swing.JButton Part41;
    private javax.swing.JButton Part6;
    private javax.swing.JButton Part7;
    private javax.swing.JButton Part8;
    private javax.swing.JLabel Tom_Clancy;
    private javax.swing.JLabel Tom_Clancy_C;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel l2;
    public javax.swing.JLabel l3;
    public javax.swing.JLabel l4;
    public javax.swing.JLabel l5;
    private javax.swing.JPanel pan4;
    private javax.swing.JPanel panel1_Assassins_Creed;
    private javax.swing.JPanel panel2_COD;
    private javax.swing.JPanel panel3_NFS;
    private javax.swing.JPanel panel4_GTA;
    private javax.swing.JPanel panel5_Tom_Clancy;
    private javax.swing.JPanel panel6_Far_Cry;
    private javax.swing.JPanel panel7_Forza_Horizon;
    private javax.swing.JPanel panel8_Horizon_Zero_Dawn;
    private javax.swing.JPanel panel9_PUB;
    // End of variables declaration//GEN-END:variables
}
