
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class Order_Placed extends javax.swing.JFrame {

    /**
     * Creates new form Ass_LastFrame
     */
    public Order_Placed() {
        initComponents();
        lab3_C.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        PC = new javax.swing.JLabel();
        FL = new javax.swing.JLabel();
        lab3 = new javax.swing.JLabel();
        lab3_C = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        PC4 = new javax.swing.JLabel();
        Amt = new javax.swing.JLabel();
        PC3 = new javax.swing.JLabel();
        UN = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(246, 246, 246));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Unispace", 0, 30)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Order Placed...");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PC.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        PC.setText("<html><body>Your package woud be shortly delivered <br>within 3 - 4 days .");
        PC.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(PC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 340, 60));

        FL.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jPanel2.add(FL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 290, 30));

        lab3.setFont(new java.awt.Font("Unispace", 1, 24)); // NOI18N
        lab3.setForeground(new java.awt.Color(255, 0, 0));
        lab3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab3.setText("Next");
        lab3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        lab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lab3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lab3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lab3MouseExited(evt);
            }
        });
        jPanel2.add(lab3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 90, 40));

        lab3_C.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        lab3_C.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lab3_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lab3_C.png"))); // NOI18N
        jPanel2.add(lab3_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 90, 40));

        l10.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        l10.setForeground(new java.awt.Color(6, 190, 18));
        l10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        l10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Right icon.png"))); // NOI18N
        l10.setText("Order Placed Sucessfuly");
        jPanel2.add(l10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 320, 50));

        PC4.setFont(new java.awt.Font("Unispace", 1, 24)); // NOI18N
        PC4.setText("Total Amount : Rs.");
        jPanel2.add(PC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, 30));

        Amt.setFont(new java.awt.Font("Unispace", 1, 25)); // NOI18N
        Amt.setForeground(new java.awt.Color(0, 122, 0));
        Amt.setText("1650");
        jPanel2.add(Amt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 90, 30));

        PC3.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        PC3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PC3.setText("Thank You! Purchase Successfull");
        jPanel2.add(PC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 110, 400, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 360, 330));

        UN.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jPanel1.add(UN, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 150, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lab3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab3MouseExited
        lab3_C.setVisible(false);
        lab3.setForeground(new java.awt.Color(255,0,0));
        lab3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
    }//GEN-LAST:event_lab3MouseExited

    private void lab3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab3MouseEntered
        lab3_C.setVisible(true);
        lab3.setForeground(new java.awt.Color(255,255,255));
        lab3.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_lab3MouseEntered

    private void lab3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lab3MouseClicked
        Thank_You f1 = new Thank_You();
        f1.FL.setText(this.FL.getText());
        f1.UN.setText(this.UN.getText());
        
        f1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lab3MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String a = "" , b = "" ;
        String c = UN.getText();        
        
        try
        {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/P","root","root");
            Statement st = con.createStatement();
            String qry = "Select * from acc where username = '" +c+ "';";
            ResultSet rs = st.executeQuery(qry);

            if(rs.next())
            {
                a = rs.getString("Fname");
                b = rs.getString("LName");
                FL.setText(a + " " + b);
            }                                                 
            
            rs.close();
            st.close();
            con.close();
        }
        catch (SQLException | ClassNotFoundException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order_Placed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order_Placed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order_Placed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order_Placed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order_Placed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Amt;
    public javax.swing.JLabel FL;
    private javax.swing.JLabel PC;
    private javax.swing.JLabel PC3;
    private javax.swing.JLabel PC4;
    public javax.swing.JLabel UN;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel lab3;
    private javax.swing.JLabel lab3_C;
    // End of variables declaration//GEN-END:variables
}
